include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    prefer_relative_imports: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    # package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_statements: true
    use_super_parameters: true
    prefer_const_constructors: false  # Annoying in early development
    prefer_single_quotes: false  # Annoying in early development
